---
title: "Model syntax"
author: "Tomasz Żółtak"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Model syntax}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# Introduction

The vignette contains model syntax generated by the `prepare_models()` function under simulation conditions included in the `conditions` data frame (that was built into package).

# nExogLVs: 3, nLIs: 1, nIndic: 3, models: unconstrained, mean centered (ML in lavaan, TSLS in MIIVsem)

```
x1 =~ x1_1 + x1_2 + x1_3
x2 =~ x2_1 + x2_2 + x2_3
x3 =~ x3_1 + x3_2 + x3_3
y =~ y_1 + y_2 + y_3
xi12 =~ xi12_1 + xi12_2 + xi12_3
x1 ~~ c1*x2
xi12 ~ c1*1
y ~ NA*1
y ~ x1 + x2 + x3 + xi12
```

# nExogLVs: 3, nLIs: 1, nIndic: 3, models: unconstrained, residual centered (ML in lavaan, TSLS in MIIVsem)

```
x1 =~ x1_1 + x1_2 + x1_3
x2 =~ x2_1 + x2_2 + x2_3
x3 =~ x3_1 + x3_2 + x3_3
y =~ y_1 + y_2 + y_3
xi12 =~ xi12_1 + xi12_2 + xi12_3
xi12 ~~ 0*x1
xi12 ~~ 0*x2
xi12 ~~ 0*x3
y ~ x1 + x2 + x3 + xi12
```

# nExogLVs: 3, nLIs: 1, nIndic: 3, models: unconstrained, double centered (ML in lavaan, TSLS in MIIVsem)

```
x1 =~ x1_1 + x1_2 + x1_3
x2 =~ x2_1 + x2_2 + x2_3
x3 =~ x3_1 + x3_2 + x3_3
y =~ y_1 + y_2 + y_3
xi12 =~ xi12_1 + xi12_2 + xi12_3
y ~ x1 + x2 + x3 + xi12
```

# nExogLVs: 3, nLIs: 1, nIndic: 3, models: PLS (cSEM)

```
x1 =~ x1_1 + x1_2 + x1_3
x2 =~ x2_1 + x2_2 + x2_3
x3 =~ x3_1 + x3_2 + x3_3
y =~ y_1 + y_2 + y_3
y ~ x1 + x2 + x3 + x1.x2
```

# nExogLVs: 3, nLIs: 1, nIndic: 3, models: SAM (lavaan)

```
x1 =~ x1_1 + x1_2 + x1_3
x2 =~ x2_1 + x2_2 + x2_3
x3 =~ x3_1 + x3_2 + x3_3
y =~ y_1 + y_2 + y_3
y ~ x1 + x2 + x3 + x1:x2
```

# nExogLVs: 3, nLIs: 1, nIndic: 3, models: Mplus (LMS & Bayes)

```
x1 BY x1_1 x1_2 x1_3;
x2 BY x2_1 x2_2 x2_3;
x3 BY x3_1 x3_2 x3_3;
y BY y_1 y_2 y_3;
xi12 | x1 XWITH x2;
y ON x1 x2 x3 xi12;
```

# nExogLVs: 3, nLIs: 1, nIndic: 5, models: unconstrained, mean centered (ML in lavaan, TSLS in MIIVsem)

```
x1 =~ x1_1 + x1_2 + x1_3 + x1_4 + x1_5
x2 =~ x2_1 + x2_2 + x2_3 + x2_4 + x2_5
x3 =~ x3_1 + x3_2 + x3_3 + x3_4 + x3_5
y =~ y_1 + y_2 + y_3 + y_4 + y_5
xi12 =~ xi12_1 + xi12_2 + xi12_3 + xi12_4 + xi12_5
x1 ~~ c1*x2
xi12 ~ c1*1
y ~ NA*1
y ~ x1 + x2 + x3 + xi12
```

# nExogLVs: 3, nLIs: 1, nIndic: 5, models: unconstrained, residual centered (ML in lavaan, TSLS in MIIVsem)

```
x1 =~ x1_1 + x1_2 + x1_3 + x1_4 + x1_5
x2 =~ x2_1 + x2_2 + x2_3 + x2_4 + x2_5
x3 =~ x3_1 + x3_2 + x3_3 + x3_4 + x3_5
y =~ y_1 + y_2 + y_3 + y_4 + y_5
xi12 =~ xi12_1 + xi12_2 + xi12_3 + xi12_4 + xi12_5
xi12 ~~ 0*x1
xi12 ~~ 0*x2
xi12 ~~ 0*x3
y ~ x1 + x2 + x3 + xi12
```

# nExogLVs: 3, nLIs: 1, nIndic: 5, models: unconstrained, double centered (ML in lavaan, TSLS in MIIVsem)

```
x1 =~ x1_1 + x1_2 + x1_3 + x1_4 + x1_5
x2 =~ x2_1 + x2_2 + x2_3 + x2_4 + x2_5
x3 =~ x3_1 + x3_2 + x3_3 + x3_4 + x3_5
y =~ y_1 + y_2 + y_3 + y_4 + y_5
xi12 =~ xi12_1 + xi12_2 + xi12_3 + xi12_4 + xi12_5
y ~ x1 + x2 + x3 + xi12
```

# nExogLVs: 3, nLIs: 1, nIndic: 5, models: PLS (cSEM)

```
x1 =~ x1_1 + x1_2 + x1_3 + x1_4 + x1_5
x2 =~ x2_1 + x2_2 + x2_3 + x2_4 + x2_5
x3 =~ x3_1 + x3_2 + x3_3 + x3_4 + x3_5
y =~ y_1 + y_2 + y_3 + y_4 + y_5
y ~ x1 + x2 + x3 + x1.x2
```

# nExogLVs: 3, nLIs: 1, nIndic: 5, models: SAM (lavaan)

```
x1 =~ x1_1 + x1_2 + x1_3 + x1_4 + x1_5
x2 =~ x2_1 + x2_2 + x2_3 + x2_4 + x2_5
x3 =~ x3_1 + x3_2 + x3_3 + x3_4 + x3_5
y =~ y_1 + y_2 + y_3 + y_4 + y_5
y ~ x1 + x2 + x3 + x1:x2
```

# nExogLVs: 3, nLIs: 1, nIndic: 5, models: Mplus (LMS & Bayes)

```
x1 BY x1_1 x1_2 x1_3 x1_4 x1_5;
x2 BY x2_1 x2_2 x2_3 x2_4 x2_5;
x3 BY x3_1 x3_2 x3_3 x3_4 x3_5;
y BY y_1 y_2 y_3 y_4 y_5;
xi12 | x1 XWITH x2;
y ON x1 x2 x3 xi12;
```

# nExogLVs: 3, nLIs: 2, nIndic: 3, models: unconstrained, mean centered (ML in lavaan, TSLS in MIIVsem)

```
x1 =~ x1_1 + x1_2 + x1_3
x2 =~ x2_1 + x2_2 + x2_3
x3 =~ x3_1 + x3_2 + x3_3
y =~ y_1 + y_2 + y_3
xi12 =~ xi12_1 + xi12_2 + xi12_3
xi13 =~ xi13_1 + xi13_2 + xi13_3
x1 ~~ c1*x2
x1 ~~ c2*x3
xi12_1 ~~ xi13_1
xi12_2 ~~ xi13_2
xi12_3 ~~ xi13_3
xi12 ~ c1*1
xi13 ~ c2*1
y ~ NA*1
y ~ x1 + x2 + x3 + xi12 + xi13
```

# nExogLVs: 3, nLIs: 2, nIndic: 3, models: unconstrained, residual centered (ML in lavaan, TSLS in MIIVsem)

```
x1 =~ x1_1 + x1_2 + x1_3
x2 =~ x2_1 + x2_2 + x2_3
x3 =~ x3_1 + x3_2 + x3_3
y =~ y_1 + y_2 + y_3
xi12 =~ xi12_1 + xi12_2 + xi12_3
xi13 =~ xi13_1 + xi13_2 + xi13_3
xi12 ~~ 0*x1
xi13 ~~ 0*x1
xi12 ~~ 0*x2
xi13 ~~ 0*x2
xi12 ~~ 0*x3
xi13 ~~ 0*x3
y ~ x1 + x2 + x3 + xi12 + xi13
```

# nExogLVs: 3, nLIs: 2, nIndic: 3, models: unconstrained, double centered (ML in lavaan, TSLS in MIIVsem)

```
x1 =~ x1_1 + x1_2 + x1_3
x2 =~ x2_1 + x2_2 + x2_3
x3 =~ x3_1 + x3_2 + x3_3
y =~ y_1 + y_2 + y_3
xi12 =~ xi12_1 + xi12_2 + xi12_3
xi13 =~ xi13_1 + xi13_2 + xi13_3
xi12_1 ~~ xi13_1
xi12_2 ~~ xi13_2
xi12_3 ~~ xi13_3
y ~ x1 + x2 + x3 + xi12 + xi13
```

# nExogLVs: 3, nLIs: 2, nIndic: 3, models: PLS (cSEM)

```
x1 =~ x1_1 + x1_2 + x1_3
x2 =~ x2_1 + x2_2 + x2_3
x3 =~ x3_1 + x3_2 + x3_3
y =~ y_1 + y_2 + y_3
y ~ x1 + x2 + x3 + x1.x2 + x1.x3
```

# nExogLVs: 3, nLIs: 2, nIndic: 3, models: SAM (lavaan)

```
x1 =~ x1_1 + x1_2 + x1_3
x2 =~ x2_1 + x2_2 + x2_3
x3 =~ x3_1 + x3_2 + x3_3
y =~ y_1 + y_2 + y_3
y ~ x1 + x2 + x3 + x1:x2 + x1:x3
```

# nExogLVs: 3, nLIs: 2, nIndic: 3, models: Mplus (LMS & Bayes)

```
x1 BY x1_1 x1_2 x1_3;
x2 BY x2_1 x2_2 x2_3;
x3 BY x3_1 x3_2 x3_3;
y BY y_1 y_2 y_3;
xi12 | x1 XWITH x2;
xi13 | x1 XWITH x3;
y ON x1 x2 x3 xi12 xi13;
```

# nExogLVs: 3, nLIs: 2, nIndic: 5, models: unconstrained, mean centered (ML in lavaan, TSLS in MIIVsem)

```
x1 =~ x1_1 + x1_2 + x1_3 + x1_4 + x1_5
x2 =~ x2_1 + x2_2 + x2_3 + x2_4 + x2_5
x3 =~ x3_1 + x3_2 + x3_3 + x3_4 + x3_5
y =~ y_1 + y_2 + y_3 + y_4 + y_5
xi12 =~ xi12_1 + xi12_2 + xi12_3 + xi12_4 + xi12_5
xi13 =~ xi13_1 + xi13_2 + xi13_3 + xi13_4 + xi13_5
x1 ~~ c1*x2
x1 ~~ c2*x3
xi12_1 ~~ xi13_1
xi12_2 ~~ xi13_2
xi12_3 ~~ xi13_3
xi12_4 ~~ xi13_4
xi12_5 ~~ xi13_5
xi12 ~ c1*1
xi13 ~ c2*1
y ~ NA*1
y ~ x1 + x2 + x3 + xi12 + xi13
```

# nExogLVs: 3, nLIs: 2, nIndic: 5, models: unconstrained, residual centered (ML in lavaan, TSLS in MIIVsem)

```
x1 =~ x1_1 + x1_2 + x1_3 + x1_4 + x1_5
x2 =~ x2_1 + x2_2 + x2_3 + x2_4 + x2_5
x3 =~ x3_1 + x3_2 + x3_3 + x3_4 + x3_5
y =~ y_1 + y_2 + y_3 + y_4 + y_5
xi12 =~ xi12_1 + xi12_2 + xi12_3 + xi12_4 + xi12_5
xi13 =~ xi13_1 + xi13_2 + xi13_3 + xi13_4 + xi13_5
xi12 ~~ 0*x1
xi13 ~~ 0*x1
xi12 ~~ 0*x2
xi13 ~~ 0*x2
xi12 ~~ 0*x3
xi13 ~~ 0*x3
y ~ x1 + x2 + x3 + xi12 + xi13
```

# nExogLVs: 3, nLIs: 2, nIndic: 5, models: unconstrained, double centered (ML in lavaan, TSLS in MIIVsem)

```
x1 =~ x1_1 + x1_2 + x1_3 + x1_4 + x1_5
x2 =~ x2_1 + x2_2 + x2_3 + x2_4 + x2_5
x3 =~ x3_1 + x3_2 + x3_3 + x3_4 + x3_5
y =~ y_1 + y_2 + y_3 + y_4 + y_5
xi12 =~ xi12_1 + xi12_2 + xi12_3 + xi12_4 + xi12_5
xi13 =~ xi13_1 + xi13_2 + xi13_3 + xi13_4 + xi13_5
xi12_1 ~~ xi13_1
xi12_2 ~~ xi13_2
xi12_3 ~~ xi13_3
xi12_4 ~~ xi13_4
xi12_5 ~~ xi13_5
y ~ x1 + x2 + x3 + xi12 + xi13
```

# nExogLVs: 3, nLIs: 2, nIndic: 5, models: PLS (cSEM)

```
x1 =~ x1_1 + x1_2 + x1_3 + x1_4 + x1_5
x2 =~ x2_1 + x2_2 + x2_3 + x2_4 + x2_5
x3 =~ x3_1 + x3_2 + x3_3 + x3_4 + x3_5
y =~ y_1 + y_2 + y_3 + y_4 + y_5
y ~ x1 + x2 + x3 + x1.x2 + x1.x3
```

# nExogLVs: 3, nLIs: 2, nIndic: 5, models: SAM (lavaan)

```
x1 =~ x1_1 + x1_2 + x1_3 + x1_4 + x1_5
x2 =~ x2_1 + x2_2 + x2_3 + x2_4 + x2_5
x3 =~ x3_1 + x3_2 + x3_3 + x3_4 + x3_5
y =~ y_1 + y_2 + y_3 + y_4 + y_5
y ~ x1 + x2 + x3 + x1:x2 + x1:x3
```

# nExogLVs: 3, nLIs: 2, nIndic: 5, models: Mplus (LMS & Bayes)

```
x1 BY x1_1 x1_2 x1_3 x1_4 x1_5;
x2 BY x2_1 x2_2 x2_3 x2_4 x2_5;
x3 BY x3_1 x3_2 x3_3 x3_4 x3_5;
y BY y_1 y_2 y_3 y_4 y_5;
xi12 | x1 XWITH x2;
xi13 | x1 XWITH x3;
y ON x1 x2 x3 xi12 xi13;
```

# nExogLVs: 3, nLIs: 3, nIndic: 3, models: unconstrained, mean centered (ML in lavaan, TSLS in MIIVsem)

```
x1 =~ x1_1 + x1_2 + x1_3
x2 =~ x2_1 + x2_2 + x2_3
x3 =~ x3_1 + x3_2 + x3_3
y =~ y_1 + y_2 + y_3
xi12 =~ xi12_1 + xi12_2 + xi12_3
xi13 =~ xi13_1 + xi13_2 + xi13_3
xi23 =~ xi23_1 + xi23_2 + xi23_3
x1 ~~ c1*x2
x1 ~~ c2*x3
x2 ~~ c3*x3
xi12_1 ~~ xi13_1
xi12_2 ~~ xi13_2
xi12_3 ~~ xi13_3
xi12_1 ~~ xi23_1
xi12_2 ~~ xi23_2
xi12_3 ~~ xi23_3
xi13_1 ~~ xi23_1
xi13_2 ~~ xi23_2
xi13_3 ~~ xi23_3
xi12 ~ c1*1
xi13 ~ c2*1
xi23 ~ c3*1
y ~ NA*1
y ~ x1 + x2 + x3 + xi12 + xi13 + xi23
```

# nExogLVs: 3, nLIs: 3, nIndic: 3, models: unconstrained, residual centered (ML in lavaan, TSLS in MIIVsem)

```
x1 =~ x1_1 + x1_2 + x1_3
x2 =~ x2_1 + x2_2 + x2_3
x3 =~ x3_1 + x3_2 + x3_3
y =~ y_1 + y_2 + y_3
xi12 =~ xi12_1 + xi12_2 + xi12_3
xi13 =~ xi13_1 + xi13_2 + xi13_3
xi23 =~ xi23_1 + xi23_2 + xi23_3
xi12 ~~ 0*x1
xi13 ~~ 0*x1
xi23 ~~ 0*x1
xi12 ~~ 0*x2
xi13 ~~ 0*x2
xi23 ~~ 0*x2
xi12 ~~ 0*x3
xi13 ~~ 0*x3
xi23 ~~ 0*x3
y ~ x1 + x2 + x3 + xi12 + xi13 + xi23
```

# nExogLVs: 3, nLIs: 3, nIndic: 3, models: unconstrained, double centered (ML in lavaan, TSLS in MIIVsem)

```
x1 =~ x1_1 + x1_2 + x1_3
x2 =~ x2_1 + x2_2 + x2_3
x3 =~ x3_1 + x3_2 + x3_3
y =~ y_1 + y_2 + y_3
xi12 =~ xi12_1 + xi12_2 + xi12_3
xi13 =~ xi13_1 + xi13_2 + xi13_3
xi23 =~ xi23_1 + xi23_2 + xi23_3
xi12_1 ~~ xi13_1
xi12_2 ~~ xi13_2
xi12_3 ~~ xi13_3
xi12_1 ~~ xi23_1
xi12_2 ~~ xi23_2
xi12_3 ~~ xi23_3
xi13_1 ~~ xi23_1
xi13_2 ~~ xi23_2
xi13_3 ~~ xi23_3
y ~ x1 + x2 + x3 + xi12 + xi13 + xi23
```

# nExogLVs: 3, nLIs: 3, nIndic: 3, models: PLS (cSEM)

```
x1 =~ x1_1 + x1_2 + x1_3
x2 =~ x2_1 + x2_2 + x2_3
x3 =~ x3_1 + x3_2 + x3_3
y =~ y_1 + y_2 + y_3
y ~ x1 + x2 + x3 + x1.x2 + x1.x3 + x2.x3
```

# nExogLVs: 3, nLIs: 3, nIndic: 3, models: SAM (lavaan)

```
x1 =~ x1_1 + x1_2 + x1_3
x2 =~ x2_1 + x2_2 + x2_3
x3 =~ x3_1 + x3_2 + x3_3
y =~ y_1 + y_2 + y_3
y ~ x1 + x2 + x3 + x1:x2 + x1:x3 + x2:x3
```

# nExogLVs: 3, nLIs: 3, nIndic: 3, models: Mplus (LMS & Bayes)

```
x1 BY x1_1 x1_2 x1_3;
x2 BY x2_1 x2_2 x2_3;
x3 BY x3_1 x3_2 x3_3;
y BY y_1 y_2 y_3;
xi12 | x1 XWITH x2;
xi13 | x1 XWITH x3;
xi23 | x2 XWITH x3;
y ON x1 x2 x3 xi12 xi13 xi23;
```

# nExogLVs: 3, nLIs: 3, nIndic: 5, models: unconstrained, mean centered (ML in lavaan, TSLS in MIIVsem)

```
x1 =~ x1_1 + x1_2 + x1_3 + x1_4 + x1_5
x2 =~ x2_1 + x2_2 + x2_3 + x2_4 + x2_5
x3 =~ x3_1 + x3_2 + x3_3 + x3_4 + x3_5
y =~ y_1 + y_2 + y_3 + y_4 + y_5
xi12 =~ xi12_1 + xi12_2 + xi12_3 + xi12_4 + xi12_5
xi13 =~ xi13_1 + xi13_2 + xi13_3 + xi13_4 + xi13_5
xi23 =~ xi23_1 + xi23_2 + xi23_3 + xi23_4 + xi23_5
x1 ~~ c1*x2
x1 ~~ c2*x3
x2 ~~ c3*x3
xi12_1 ~~ xi13_1
xi12_2 ~~ xi13_2
xi12_3 ~~ xi13_3
xi12_4 ~~ xi13_4
xi12_5 ~~ xi13_5
xi12_1 ~~ xi23_1
xi12_2 ~~ xi23_2
xi12_3 ~~ xi23_3
xi12_4 ~~ xi23_4
xi12_5 ~~ xi23_5
xi13_1 ~~ xi23_1
xi13_2 ~~ xi23_2
xi13_3 ~~ xi23_3
xi13_4 ~~ xi23_4
xi13_5 ~~ xi23_5
xi12 ~ c1*1
xi13 ~ c2*1
xi23 ~ c3*1
y ~ NA*1
y ~ x1 + x2 + x3 + xi12 + xi13 + xi23
```

# nExogLVs: 3, nLIs: 3, nIndic: 5, models: unconstrained, residual centered (ML in lavaan, TSLS in MIIVsem)

```
x1 =~ x1_1 + x1_2 + x1_3 + x1_4 + x1_5
x2 =~ x2_1 + x2_2 + x2_3 + x2_4 + x2_5
x3 =~ x3_1 + x3_2 + x3_3 + x3_4 + x3_5
y =~ y_1 + y_2 + y_3 + y_4 + y_5
xi12 =~ xi12_1 + xi12_2 + xi12_3 + xi12_4 + xi12_5
xi13 =~ xi13_1 + xi13_2 + xi13_3 + xi13_4 + xi13_5
xi23 =~ xi23_1 + xi23_2 + xi23_3 + xi23_4 + xi23_5
xi12 ~~ 0*x1
xi13 ~~ 0*x1
xi23 ~~ 0*x1
xi12 ~~ 0*x2
xi13 ~~ 0*x2
xi23 ~~ 0*x2
xi12 ~~ 0*x3
xi13 ~~ 0*x3
xi23 ~~ 0*x3
y ~ x1 + x2 + x3 + xi12 + xi13 + xi23
```

# nExogLVs: 3, nLIs: 3, nIndic: 5, models: unconstrained, double centered (ML in lavaan, TSLS in MIIVsem)

```
x1 =~ x1_1 + x1_2 + x1_3 + x1_4 + x1_5
x2 =~ x2_1 + x2_2 + x2_3 + x2_4 + x2_5
x3 =~ x3_1 + x3_2 + x3_3 + x3_4 + x3_5
y =~ y_1 + y_2 + y_3 + y_4 + y_5
xi12 =~ xi12_1 + xi12_2 + xi12_3 + xi12_4 + xi12_5
xi13 =~ xi13_1 + xi13_2 + xi13_3 + xi13_4 + xi13_5
xi23 =~ xi23_1 + xi23_2 + xi23_3 + xi23_4 + xi23_5
xi12_1 ~~ xi13_1
xi12_2 ~~ xi13_2
xi12_3 ~~ xi13_3
xi12_4 ~~ xi13_4
xi12_5 ~~ xi13_5
xi12_1 ~~ xi23_1
xi12_2 ~~ xi23_2
xi12_3 ~~ xi23_3
xi12_4 ~~ xi23_4
xi12_5 ~~ xi23_5
xi13_1 ~~ xi23_1
xi13_2 ~~ xi23_2
xi13_3 ~~ xi23_3
xi13_4 ~~ xi23_4
xi13_5 ~~ xi23_5
y ~ x1 + x2 + x3 + xi12 + xi13 + xi23
```

# nExogLVs: 3, nLIs: 3, nIndic: 5, models: PLS (cSEM)

```
x1 =~ x1_1 + x1_2 + x1_3 + x1_4 + x1_5
x2 =~ x2_1 + x2_2 + x2_3 + x2_4 + x2_5
x3 =~ x3_1 + x3_2 + x3_3 + x3_4 + x3_5
y =~ y_1 + y_2 + y_3 + y_4 + y_5
y ~ x1 + x2 + x3 + x1.x2 + x1.x3 + x2.x3
```

# nExogLVs: 3, nLIs: 3, nIndic: 5, models: SAM (lavaan)

```
x1 =~ x1_1 + x1_2 + x1_3 + x1_4 + x1_5
x2 =~ x2_1 + x2_2 + x2_3 + x2_4 + x2_5
x3 =~ x3_1 + x3_2 + x3_3 + x3_4 + x3_5
y =~ y_1 + y_2 + y_3 + y_4 + y_5
y ~ x1 + x2 + x3 + x1:x2 + x1:x3 + x2:x3
```

# nExogLVs: 3, nLIs: 3, nIndic: 5, models: Mplus (LMS & Bayes)

```
x1 BY x1_1 x1_2 x1_3 x1_4 x1_5;
x2 BY x2_1 x2_2 x2_3 x2_4 x2_5;
x3 BY x3_1 x3_2 x3_3 x3_4 x3_5;
y BY y_1 y_2 y_3 y_4 y_5;
xi12 | x1 XWITH x2;
xi13 | x1 XWITH x3;
xi23 | x2 XWITH x3;
y ON x1 x2 x3 xi12 xi13 xi23;
```
